version: '3'
services:
  # RabbitMQ Docker
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - espacenternet  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # SQL Server Docker
  espacenter-sql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - espacenternet

  # API Docker
  espacenter-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eSpaCenterDB=Server=espacenter-sql,1433;Database=eSpaCenterDB;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=espacenter@outlook.com
      - SMTP_PASSWORD=mynewpassword321
    ports:
      - 7132:7132
    networks:
      - espacenternet
    links:
      - espacenter-sql
    depends_on:
      - espacenter-sql

  # RabbitMQ Service Docker
  rabbitmq-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eSpaCenter.Subscriber/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=espacenter@outlook.com
      - SMTP_PASSWORD=mynewpassword321
    depends_on:
      - rabbitmq
    networks:
      - espacenternet

volumes:
  rabbitmq_data:

networks:
  espacenternet:
    driver: bridge
