version: '3'
services:
#mssql docker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - espacenternet

  espacenter-sql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - espacenternet



  espacenter-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eSpaCenterDB=Server=espacenter-sql,1433;Database=eSpaCenterDB;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VIRTUALHOST=/
      - SMTP_SERVER=smtp.outlook.com
      - SMTP_PORT=587
      - SMTP_USERNAME=espacenter@outlook.com
      - SMTP_PASSWORD=mynewpassword321
    ports:
      - 7132:7132
    networks:
      - espacenternet
    links:
      - espacenter-sql
    depends_on:
      - espacenter-sql
      - rabbitmq
      
networks:
  espacenternet:
    driver: bridge   